---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
  name: simple-build
spec:
  params:
    - description: Repository URL to clone from.
      name: git-repo
      type: string
    - default: main
      description: Revision to checkout. (branch, tag, sha, ref, etc...)
      name: git-revision
      type: string
    - description: Reference of the image the pipeline will produce.
      name: output-image
      type: string
  results:
    - description: Reference of the image the pipeline will produce.
      name: IMAGE_URL
      value: $(tasks.image-build.results.IMAGE_URL)
    - description: Digest of the image the pipeline will produce.
      name: IMAGE_DIGEST
      value: $(tasks.image-build.results.IMAGE_DIGEST)
    - description: Repository URL used for buiding the image.
      name: CHAINS-GIT_URL
      value: $(tasks.git-clone.results.url)
    - description: Repository commit used for building the image.
      name: CHAINS-GIT_COMMIT
      value: $(tasks.git-clone.results.commit)
  tasks:
    - name: git-clone
      taskRef:
        bundle: gcr.io/tekton-releases/catalog/upstream/git-clone:0.9@sha256:1ee0f45892faf152aa631b0745f192e353c684408286bc55e9041edfaf22cb5e
        kind: Task
        name: git-clone
      params:
        - name: url
          value: $(params.git-repo)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: output
          workspace: shared
    - name: source-security-scan
      runAfter:
        - git-clone
      taskRef:
        bundle: gcr.io/tekton-releases/catalog/upstream/trivy-scanner:0.2@sha256:a1e4b9950f25dc7b43984c6ce978d68057e6f8349ebdc785b856acc4b5c34740
        kind: Task
        name: trivy-scanner
      params:
        - name: ARGS
          value:

        - name: IMAGE_PATH
          value: "."
      workspaces:
        - name: manifest-dir
          workspace: shared
    - name: image-build
      runAfter:
        - source-security-scan
      taskRef:
        bundle: gcr.io/tekton-releases/catalog/upstream/buildah:0.5@sha256:ccae4dfdbd085323ddfff00468b0680c1739990a73b82753e9d4271a584a33b6
        kind: Task
        name: buildah
      params:
        - name: IMAGE
          value: $(params.output-image)
        - name: STORAGE_DRIVER
          value: vfs
      workspaces:
        - name: source
          workspace: shared
    - name: image-security-scan
      taskRef:
        name: trivy-scanner
        bundle: gcr.io/tekton-releases/catalog/upstream/trivy-scanner:0.2@sha256:a1e4b9950f25dc7b43984c6ce978d68057e6f8349ebdc785b856acc4b5c34740
      params:
        - name: ARGS
          value:
            - image
        - name: IMAGE_PATH
          value: $(tasks.image-build.results.IMAGE_URL)
      workspaces:
        - name: manifest-dir
          workspace: shared
  workspaces:
    - name: shared
